[supervisord]
nodaemon=true
user=root

[program:openvpn]
command=/usr/sbin/openvpn --config /tmp/openvpn-config.ovpn --cd /config
autostart=false
autorestart=true
stderr_logfile=/var/log/openvpn-stderr.log
stdout_logfile=/var/log/openvpn-stdout.log

[program:ddns-monitor]
command=/ddns-monitor.sh
autostart=false
autorestart=true
stderr_logfile=/var/log/ddns-monitor-stderr.log
stdout_logfile=/var/log/ddns-monitor-stdout.log
